spring.application.name=service-location-neumatica

# =========================================================
# SERVER
# =========================================================

server.port=8082


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a:5432/bbdd_neumatica_whatsapp
spring.datasource.username=neumatica
spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# JWT
# =========================================================

# IMPORTANTE:
# Debe ser la misma clave utilizada por tu auth-service
# para firmar el JWT si estás utilizando HS256.

jwt.secret=CAMBIA_ESTA_CLAVE_POR_UNA_MUY_LARGA_Y_SEGURA
app.jwt.issuer=security-service
app.jwt.public-key=classpath:keys/public.pem