spring.application.name=service-location-neumatica

server.port=8082

spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a:5432/bbdd_neumatica_whatsapp
spring.datasource.username=neumatica
spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=CAMBIA_ESTA_CLAVE_POR_UNA_MUY_LARGA_Y_SEGURA
app.jwt.issuer=security-service
app.jwt.public-key=classpath:keys/public.pem

services.security.url=https://security-service-neumatica.onrender.com